services:
    mariadb:
      container_name: mariadb
      build:
        context: "./requirements/mariadb"
      volumes:
        - "mariadb:/mnt/vol"
      networks:
        - reseau
      env_file:
        - "../.env"

volumes:
    mariadb:
      driver: local
      driver_opts:
        type: none
        device: "~/data/mariadb"
        o: bind

networks:
    reseau:
      driver: bridge
